language: objective-c

branches:
  only:
    - master

xcode_project: ScalePicker.xcodeproj
xcode_scheme: ScalePicker
osx_image: xcode8.0
xcode_sdk: iphonesimulator10.0

script:
  - xcodebuild build -project ScalePicker.xcodeproj -scheme "ScalePicker" -destination "platform=iOS Simulator,name=iPhone 7"
