language: objective-c

branches:
  only:
    - master

xcode_project: ScalePicker.xcodeproj
xcode_scheme: ScalePicker
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

script:
  - xcodebuild build -project ScalePicker.xcodeproj -scheme "ScalePicker" -destination "platform=iOS Simulator,name=iPhone 6s"
