language: objective-c

branches:
  only:
    - master

xcode_project: ScalePicker.xcodeproj
xcode_scheme: ScalePicker
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2

script:
  - xcodebuild test -project ScalePicker.xcodeproj -scheme "ScalePicker" -destination "platform=iOS Simulator,name=iPhone 6s"